version: '3.6'

services:
  # mongo service
  mongodb-local:
    image: mongo:4.4
    container_name: mongodb-local
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodata:/data/db
    networks:
      - mongo_net
  # redis service
  redis-local:
    image: 'redis:alpine'
    container_name: redis-local
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always

volumes:
  mongodata:
  redis-data:
  redis.conf:

networks:
  mongo_net:
    driver: bridge
